version: '3.1'

services:

  postgres:
    image: postgres:9.6.8
    restart: always
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: abakulin
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432

      # POSTGRES_INITDB_ARGS: --auth-host=md5